USE DB_LAB2
GO
SET STATISTICS IO ON;

CREATE NONCLUSTERED INDEX IX_SANPHAM_TENSP ON dbo.SANPHAM(tenSP ASC, MaSP ASC) INCLUDE(giaBan,loaiSP,MaKho,MaDM)
CREATE NONCLUSTERED INDEX IX_CTDH_TENSP ON dbo.CTDH(tenSP ASC, MaSP ASC) INCLUDE (MaDH)

CREATE NONCLUSTERED INDEX IX_CTDH_FULL ON dbo.CTDH(tenSP ASC, MaSP ASC) INCLUDE (MaDH,giaSanPham,giaGiam,soLuong,thanhtien)

CREATE NONCLUSTERED INDEX IX_CTKHO_FULL ON dbo.CTKHO(MaKho ASC, MaSP ASC) INCLUDE(tenSP,soLuongTon)



CREATE NONCLUSTERED INDEX IX_KHACHHANG_PASS ON dbo.KHACHHANG(dienthoaiKH ASC, matkhau ASC, MaKH ASC) 


CREATE NONCLUSTERED INDEX IX_NHANVIEN
ON [dbo].[NHANVIEN] ([dienthoaiNV],[LoaiNV],[MatKhau])

CREATE NONCLUSTERED INDEX IX_CTNX ON dbo.CTNX(tenSP ASC, SoLuong ASC)

CREATE NONCLUSTERED INDEX IX_LICHSUNHAPXUAT ON dbo.LICHSUNHAPXUAT(loai ASC,MaKho ASC, ngayThucHien ASC,nhanVienPhuTrach ASC,diaChiNhapXuat ASC)

-----
--1
CREATE NONCLUSTERED INDEX IX_KHACHHANG_LOGIN ON dbo.KHACHHANG(dienthoaiKH ASC) include(matkhau)

CREATE NONCLUSTERED INDEX IX_NHANVIEN_LOGIN ON dbo.NHANVIEN(dienthoaiNV ASC) INCLUDE(MatKhau,LoaiNV)

--2
CREATE NONCLUSTERED INDEX IX_DANHMUC_NULL ON dbo.DANHMUC(tenDM ASC) WHERE DMcha IS NULL

--3 
CREATE NONCLUSTERED INDEX IX_DANHMUC_TENDM ON dbo.DANHMUC(tenDM ASC,MaDM ASC)

--4
CREATE NONCLUSTERED INDEX IX_SANPHAM_LOAISP ON dbo.SANPHAM(loaiSP ASC) INCLUDE(masp, tenSP, giaBan, MaKho,madm)

--5
CREATE NONCLUSTERED INDEX IX_CTDH_ALL ON dbo.CTDH(MaDH ASC) INCLUDE(tensp, giaSanPham,soLuong,giagiam,thanhtien)

--6
CREATE NONCLUSTERED INDEX IX_DIEMDANH ON dbo.DIEMDANH(ngayDiemDanh ASC,MaNV asc)

